
services:
  db:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MARIADB_ROOT_PASSWORD: sex
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
